language: python

python:
  - "3.6"
before_install:
  - pip install codecov
install:
  - pip install -q coverage
  - pip install -r requirements.txt
  - pip install .
script: tests/run_test.sh
after_success:
  - codecov
branches:
  only:
    - master